name: CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for API
        id: meta_api
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}-api

      - name: Build and push API image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: family-tree-api/Dockerfile
          push: true
          tags: ${{ steps.meta_api.outputs.tags }}
          labels: ${{ steps.meta_api.outputs.labels }}

      - name: Extract metadata (tags, labels) for UI
        id: meta_ui
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}-ui

      - name: Build and push UI image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: family-tree-ui/Dockerfile
          push: true
          tags: ${{ steps.meta_ui.outputs.tags }}
          labels: ${{ steps.meta_ui.outputs.labels }}


